# Generated by Django 4.0.6 on 2022-08-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=50)),
                ('Contraseña', models.CharField(max_length=50)),
                ('Categoria', models.IntegerField(blank=True, null=True)),
                ('Usuario_FK', models.IntegerField(blank=True, null=True)),
                ('Nombre_Completo', models.CharField(max_length=50)),
                ('Telefoo', models.CharField(blank=True, max_length=10, null=True)),
                ('Foto', models.ImageField(upload_to='')),
                ('Verificado', models.BooleanField(default=False)),
                ('Pose1', models.ImageField(upload_to='')),
                ('Pose2', models.ImageField(upload_to='')),
                ('Selfie1', models.ImageField(upload_to='')),
                ('Selfie2', models.ImageField(upload_to='')),
                ('Dpi', models.ImageField(upload_to='')),
                ('Mensaje', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
