# Generated by Django 4.0.6 on 2022-08-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Telefoo',
            new_name='Telefono',
        ),
    ]
