# Generated by Django 4.0.6 on 2022-08-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_rename_telefoo_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Dpi',
            field=models.ImageField(null=True, upload_to='Usuarios'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Foto',
            field=models.ImageField(null=True, upload_to='Usuarios'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Pose1',
            field=models.ImageField(null=True, upload_to='Usuarios'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Pose2',
            field=models.ImageField(null=True, upload_to='Usuarios'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Selfie1',
            field=models.ImageField(null=True, upload_to='Usuarios'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Selfie2',
            field=models.ImageField(null=True, upload_to='Usuarios'),
        ),
    ]
