# Generated by Django 4.0.6 on 2022-08-05 06:14

import Usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_usuario_dpi_alter_usuario_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Dpi',
            field=models.ImageField(blank=True, null=True, upload_to=Usuarios.models.ruta_personalizada_Dpi),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to=Usuarios.models.ruta_personalizada_foto),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Pose1',
            field=models.ImageField(blank=True, null=True, upload_to=Usuarios.models.ruta_personalizada_P1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Pose2',
            field=models.ImageField(blank=True, null=True, upload_to=Usuarios.models.ruta_personalizada_P2),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Selfie1',
            field=models.ImageField(blank=True, null=True, upload_to=models.ImageField(blank=True, null=True, upload_to=Usuarios.models.ruta_personalizada_S1)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Selfie2',
            field=models.ImageField(blank=True, null=True, upload_to=Usuarios.models.ruta_personalizada_S2),
        ),
    ]
