# Generated by Django 4.0.6 on 2022-08-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_alter_usuario_dpi_alter_usuario_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Usuario',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
