# Generated by Django 4.0.6 on 2022-08-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_usuario_docidentificacion_alter_usuario_selfie1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Verificado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
